name: Deploy Docs

on:
  create:

jobs:
  publish:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Fetch Tags
        run: git fetch --unshallow --tags

      - name: Install nix
        uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Autogenerate versioned docs folder with tag
        run: GIT_TAG=`echo $(git describe --tags --abbrev=0)` nix-shell --run docs-version

      - name: Commit versioned docs folder
        if: success()
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update versioned docs folder (automated)

      - name: Build Docs site
        if: success()
        run: nix-shell --run docs-build

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: docusaurus/build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
